1.0.0
Iconica-Development/flutter_rbac pull request #4
Opened 2024-03-11 10:14 UTC by JacquesDIconica

2024-03-11 10:15 UTC, freekvandeven commented
@JacquesDIconica please squash the commit messages

2024-03-11 12:11 UTC, freekvandeven commented on packages/flutter_rbac_services_data_interface/lib/src/models/permission_model.dart
> +  PermissionModel({
const

2024-03-11 12:11 UTC, freekvandeven commented on packages/flutter_rbac_services_data_interface/lib/src/models/role_data_model.dart
>    RoleDataModel({
const

2024-03-11 12:11 UTC, freekvandeven commented on packages/flutter_rbac_services_data_interface/lib/src/models/securable_object_data_model.dart
> +  SecurableObjectDataModel({
const

2024-03-11 12:11 UTC, freekvandeven commented on packages/flutter_rbac_services_data_interface/pubspec.yaml
> +version: 1.0.01
1.0.0

2024-03-11 12:12 UTC, freekvandeven commented
@Gorter-dev @JacquesDIconica maybe it should also be an option to provide the collectionnames so people can have multiple rbac instances in the same firestore database like we did with Safino.

2024-03-12 15:00 UTC, Gorter-dev requested changes
Example can be removed, please improve README

2024-03-12 15:00 UTC, Gorter-dev commented on README.md
> +Flutter RBAC Service is a package that enables to add a RBAC system to an excisting project. Currently only a Firebase Firestore datasource is provided, but a custom datasource can be constructed by
typo

2024-03-12 15:00 UTC, Gorter-dev commented on README.md
> +  flutter_rbac_services:
services should be service

2024-03-12 15:00 UTC, Gorter-dev commented on README.md
> +        FirebaseRbacDatasource(
Casing

2024-03-12 15:00 UTC, Gorter-dev commented on README.md
> +From here any methods can be called from this service to set up and use RBAC.
What method and how?

2024-03-12 15:00 UTC, Gorter-dev commented on packages/flutter_rbac_services/lib/flutter_rbac_services.dart
> -library flutter_rbac_services;
Library should be there?

2024-03-12 15:00 UTC, Gorter-dev commented on packages/flutter_rbac_services/pubspec.yaml
> +    path: ../flutter_rbac_services_data_interface
Before creating PR, should be reset to GIT

2024-03-12 15:00 UTC, Gorter-dev commented on packages/flutter_rbac_services_data_interface/lib/flutter_rbac_services_data_interface.dart
> +export 'src/models/account_data_model.dart';
Library should still be there

2024-03-12 15:00 UTC, Gorter-dev commented on packages/flutter_rbac_services_firebase/lib/flutter_rbac_services_firebase.dart
> -library flutter_rbac_services_firebase;
Library should still be there

2024-03-12 15:00 UTC, Gorter-dev commented on packages/flutter_rbac_services_rest/test/flutter_rbac_services_rest_test.dart
>  void main() {
this can be removed right?

2024-03-12 15:00 UTC, Gorter-dev commented on packages/flutter_rbac_services_rest/lib/flutter_rbac_services_rest.dart
>  /// A Calculator.
what is this?

2024-03-14 07:57 UTC, Gorter-dev approved these changes

2024-03-14 07:57 UTC, merged